### PR TITLE
added more tests & R-script updated & charts regenerated & readme updated

### PR DESCRIPTION
**Pull request by niXman**

### CODE REVIEW

**Comment by niXman** [comment]
ping?

**Comment by niXman** [comment]
@AntonBikineev ping

**Comment by AntonBikineev** [comment]
Hi niXman,
First, sorry for my late reply. Second, many thanks for updating this repo with your amazing tests! One time I was thinking of adding flatbuffer test to the repo, but again - couldn't find time for it. So, below are my comments and findings regarding your PR.
I checkout it out on my fresh Ubuntu 16.04.1 LTS installation, with newly installed HPX from trunk (commit 884a26a9ef8f0d939001bbcb0c9d934d11c36cde) and Boost 1.61 (for HPX). Just in case I also installed hwloc, tcmalloc and all stuff HPX would require to squeeze all performance out of my Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz. In the PR you mentioned that you use hpx 1.0.0 and that's kind of weird, because the interface of output_archive has changed since 1.0.0 and that's why I needed to slightly update hpx_zero_copy benchmark.
The results I got after running the benchmark for one million iterations are as follows:
screenshot from 2016-09-20 22-58-02
Here you can notice that the results differ substantially for hpx test as well as for hpx_zero_copy. So it seems to me that it might be the case that you used outdated version of HPX, or even more likely debug build.
If you don't mind I'll merge your PR with my corrections on top of it.
Thanks!

**Comment by niXman** [comment]
Hi,

It is strange...

My PC is `kubuntu-x86_64-14.04.03 LTS/GCC-4.8.5/core-i5 3.40GHz`.

Just now I have rebuilt the boost-1.61 and the HPX from `master` branch. Also I fix the `hpx_zero_copy/record.cpp` file in `cc-serializers`.

The HPX configured as `cd hpx && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..`
The HPX config report:
hpx-config

Test report:
test-report

I don't t know why we have such differences in the test results...

**Comment by niXman** [comment]
This is the result of tests on another computer(`core i7-4790`):
test-result

**Comment by niXman** [comment]
As an additional argument, see test results given in this PR(https://github.com/STEllAR-GROUP/cpp-serializers/pull/2). The proportion is approximately the same...

**Comment by niXman** [comment]
@AntonBikineev any news? what's the hold-up?

**Comment by AntonBikineev** [comment]
@niXman, on this weekend, when I have free time, I'll run tests on another machine, but not sure, that situation will change compared to my last results. Yo understand that I can't merge arbitrary results.

**Comment by pmed** [comment]
Results on my laptop with CPU i7-2630QM 2.00GHz × 8 and 8Gb RAM

```
pm@inspiron:~/dev/cpp-serializers/build$ uname -a
Linux inspiron 4.8.0-25-generic #27-Ubuntu SMP Thu Oct 13 03:34:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
pm@inspiron:~/dev/cpp-serializers/build$ ./test 1000000
performing 1000000 iterations

thrift-binary: version = 0.9.3
thrift-binary: size = 17017 bytes
thrift-binary: time = 25373 milliseconds

thrift-compact: version = 0.9.3
thrift-compact: size = 11597 bytes
thrift-compact: time = 35516 milliseconds

protobuf: version = 2006000
protobuf: size = 12571 bytes
protobuf: time = 29613 milliseconds

capnproto: version = 5002
capnproto: size = 17768 bytes
capnproto: time = 47 milliseconds

boost: version = 106100
boost: size = 17470 bytes
boost: time = 14249 milliseconds

msgpack: version = 1.1.0
msgpack: size = 11802 bytes
msgpack: time = 31742 milliseconds

cereal: size = 17416 bytes
cereal: time = 12596 milliseconds

avro: size = 12288 bytes
avro: time = 38101 milliseconds

hpx: version = 1.0.0
hpx: size    = 17433 bytes
hpx: time = 11636 milliseconds

hpx_zero_copy: version = 1.0.0
hpx_zero_copy: size    = 9433 bytes
hpx_zero_copy: time = 8541 milliseconds

mpi: version = 1.10.3
mpi: size    = 13008 bytes
mpi: time = 16073 milliseconds

yas: size = 17012 bytes
yas: time = 5282 milliseconds

flatbuffers: version = 1.0.0
flatbuffers: size    = 17632 bytes
flatbuffers: time = 20526 milliseconds
```

I got an exception "Error: vector::_M_default_append" for HPX tests on the master branch, so had to use the same ref as @niXman: STEllAR-GROUP/hpx@884a26a9ef8f0d939001bbcb0c9d934d11c36cde

**Comment by niXman** [comment]
@pmed Thanks!

Eventually, I checked the test results on four PCs, and I always got the same results, in no way similar to those that led Anton Bikineev...

**Comment by niXman** [comment]
Merged and closed.

**Pull request merged**
